apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ictlab-server
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vking34/ictlab-deployment.git
    targetRevision: HEAD
    path: server/
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: ms
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
