node('jenkins-slave') {

    git_info = checkout scm

    // sh "echo ${git_info.GIT_COMMIT}"

    sh "git rev-parse --short HEAD > commit-id"
    tag = readFile('commit-id').replace("\n", "").replace("\r", "")

    stage('Build') {
        // Build docker image
        sh (script: """
        docker build . -t vking34/ictlab-frontend:${tag}
        """)

        docker.withRegistry("", "dockerhub"){
            sh "docker push vking34/ictlab-frontend:${tag}"
        }

        // Mail
        // mail bcc: '', body: 'Success!', cc: '', from: '', replyTo: '', subject: '[sample-app](Build)', to: 'lzzvkingzzl@gmail.com'
    }

    stage('Test') {
        // Test here
        sh(script: """
        echo "Done!"
        ls
        """)

        // Mail
        // mail bcc: '', body: 'Success!', cc: '', from: '', replyTo: '', subject: '[sample-app](Test)', to: 'lzzvkingzzl@gmail.com'
    }


    stage('Delivery to Staging'){
        // Clone and edit image:tag in staging directory then push
        withCredentials([usernamePassword(credentialsId: 'git', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
            sh(script: """
            cd ../
            git clone https://github.com/vking34/ictlab-deployment.git
            cd ./ictlab-deployment
            git config --global user.name "vking34"
            git config --global user.email "lzzvkingzzl@gmail.com"
            sed -i -z -E "s/ictlab-frontend:[^\\n]+\\n/ictlab-frontend:${tag}\\n/g" frontend/deployment.yaml
            git add .
            git commit -m \"fix(staging): Delivery to staging env with commit ${tag}\"
            git push https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/vking34/ictlab-deployment.git
            """)
        }

        // Mail
        // mail bcc: '', body: 'Success!', cc: '', from: '', replyTo: '', subject: '[sample-app](Delivery)', to: 'lzzvkingzzl@gmail.com'
    }
}
